### ISSUE TITLE
Couldn't complete step 8.

### ISSUE THREAD

**Issue by MikeVaz** [aws-samples/aws-amplify-graphql#10]
Step 8. "Navigate to the Schema page again and on the right hand side find listPictures(...):[PictureConnection] under the Query type and click the resolver to edit it. Update the REQUEST mapping template with the code in ./AppSync/Query.listPictures.request. Use "Return single item" as the response template. Press Save at the bottom.

This will use fine grained authorization controls to filter GraphQL responses so that users only see their data from DynamoDB."

Should I click attach?
![image](https://user-images.githubusercontent.com/4261252/38507380-fea86cf8-3be1-11e8-9dcc-4b9063939f82.png)

Seem like selecting Data source name step is missing in description.
![image](https://user-images.githubusercontent.com/4261252/38507450-2695c6de-3be2-11e8-92be-fd56fa0d1899.png)

**Comment by elorzafe** [comment]
Hi @MikeVaz, thanks for your feedback. You are correct you should click the **Attach** button under **Resolver** column. Also you need to select PictureTable as Data source. I will modify it to make it more clear. 

Thanks!

**Comment by elorzafe** [comment]
Readme updated. Thanks @MikeVaz
