### ISSUE TITLE
Network error: GraphQL error: No access to ETag property on response. Check CORS configuration to expose ETag header.

### ISSUE THREAD

**Issue by alexvpickering** [aws-samples/aws-amplify-graphql#2]
Error occurred on clicking "Add Photo".

Solved by going to S3 `photoclient-userfiles-mobilehub-*` --> `Permissions` --> `CORS configuration` and adding `<ExposeHeader>ETag</ExposeHeader>` below other `ExposeHeader` declarations.

**Comment by elorzafe** [comment]
Hi @alexvpickering did you create the project using mobilehub or using awsmobile-cli?

**Comment by elorzafe** [comment]
Added Note at the bottom of the README with the solution for this problem.
