### ISSUE TITLE
react native version

### ISSUE THREAD

**Issue by Paul-Bird** [aws-samples/aws-amplify-graphql#4]
I really could do with a react native version of the same integration of Cognito sign-up / sign-in with AppSync. I have been looking, are there any resources online for this?

Paul

**Comment by elorzafe** [comment]
Hi @Paul-Bird 

Currently there are two starters than demonstrates this functionality separated.
- https://github.com/aws-samples/aws-mobile-appsync-events-starter-react-native
- https://github.com/aws-samples/aws-mobile-react-native-starter

The first sample shows AppSync functionality on a react-native app and the second shows Cognito sign-up/ sign-in using aws-amplify-react-native HOC.

**Comment by Paul-Bird** [comment]
@elorzafe  Thanks, yes I have see those two.

Was very handy having this react sample, appreciate work put in to it. 

I'll try and put AppSync, Cognito & RN together, I'm sure what I am trying to do is an obvious use case.

Paul
