### ISSUE TITLE
Can we run the client via npm scripts in the package?

### ISSUE THREAD

**Issue by MikeVaz** [aws-samples/aws-amplify-graphql#5]
Since I don't want to install yarn.

**Comment by MikeVaz** [comment]
Since I don't want to install yarn.

**Comment by elorzafe** [comment]
Hi @MikeVaz currently the cli is using by default yarn on react projects. I will check that with awsmobile-cli team to fix that problem

**Comment by elorzafe** [comment]
Hi @MikeVaz with the latest awsmobile-cli (v1.1.0) is not required to have yarn. It will use npm in case you don't have yarn.
