### ISSUE TITLE
Step 11: file downloads as `appsync.js` breaks build

### ISSUE THREAD

**Issue by sbussard** [aws-samples/aws-amplify-graphql#7]
![image](https://user-images.githubusercontent.com/345018/38346146-d7b3c5e8-3858-11e8-8f6d-8607f1ee2ccc.png)

According to the instructions the downloaded file should be called `AppSync.js` but the filename that gets downloaded is all lowercase.

**Comment by elorzafe** [comment]
Hi @sbussard thanks for the comment. App.js is now updated to use appsync.js
