### ISSUE TITLE
Step 5 doesn't work.

### ISSUE THREAD

**Issue by MikeVaz** [aws-samples/aws-amplify-graphql#8]
The UI we see in AWS console doesn't match description 
"5. Click the Attach button next to addPicture on the right of the schema editor and select PictureTable as the data source. For the request mapping template use the code in ./AppSync/Mutation.addPicture.request and for the response mapping template select Return single item from the drop-down. Press Save at the bottom."

Can't select "PictureTable" as data source. Can't set request mapping template.

**Comment by elorzafe** [comment]
Hi @MikeVaz Did you saw **Save Complete** after hitting save on schema window?

**Comment by MikeVaz** [comment]
After repeating the step I was able to "select PictureTable as the data source" but couldn't do the next step "the response mapping template select Return single item from the drop-down."

![image](https://user-images.githubusercontent.com/4261252/38506780-6c25aebe-3be0-11e8-9c3e-46b5a9a19290.png)

**Comment by MikeVaz** [comment]
It is not Amazon Dynamo DB for me. And previous steps didn't mention that.

Anyway trying to change it now.
![image](https://user-images.githubusercontent.com/4261252/38510984-42fa7cde-3bec-11e8-97ab-f36d27d40f98.png)

What should be here?

**Comment by elorzafe** [comment]
If you did step 3 and 4 it should be correct. I would retry those steps and then it should be fine, I think the problem was that Step 4 had a problem.

**Comment by MikeVaz** [comment]
I deleted the API and repeated the steps. I am stuck on step #4. 

"Still on the Schema page, press Create Resources in the upper right corner.
Select the Picture type from the drop down.
Then click on Additional Indexes followed by Add Index, set the index name as owner-index with Primary key as owner and sort key as id.
And finally click Create at the bottom.
This will create DynamoDB tables, some default queries/mutations and connect them to Resolvers"

![image](https://user-images.githubusercontent.com/4261252/38570569-c6d3753e-3cb3-11e8-802c-534ef9827c7a.png)

It looks likes this table already exists and I can't find a way to delete it.

**Comment by elorzafe** [comment]
Hi @MikeVaz we updated awsmobile-cli, and the README has new instructions to run the app with the latest version.
