### ISSUE TITLE
Blank page after sign in

### ISSUE THREAD

**Issue by sbussard** [aws-samples/aws-amplify-graphql#9]
I signed up for an account, then signed in, then entered in the mfa code, then the page went blank. 

Here's a screenshot of the javascript console in Chrome
![image](https://user-images.githubusercontent.com/345018/38450298-2e238e5c-39e1-11e8-8675-aafe7bb9d948.png)

When I refresh, the page appears and I'm logged in.

**Comment by elorzafe** [comment]
I updated package.json and yarn.lock to fix this problem. Please pull the latest code and feel free to reopen the issue if that didn't solve the problem.
